### PR TITLE
Month and week report

### LINKED ISSUE #22: Report for "one month"
It would be convenient to be able to report for "a month" at a time.  

Of course, this is already possible to do (`--from 2019-10-01 --to 2019-10-31` for October) but it would be convenient to be able to do just `utt report --month 2019-10` or `utt report --month Oct`.  

It would be pretty easy to implement the `--month` command line switch.  However it would be even more user friendly if we could write `utt report Oct`.  

Is there any interest in this?  Which is the better approach?  `--month` switch or automatic parsing?

(In either case I volunteer to do the work!)

UPDATE: Solved in #25.

### PR DESCRIPTION
**Pull request by ukrutt**
Adds switches `--month` and `--week` that will give a report for a whole month or week.  Possible arguments:

 - `--month`:
    - `this`, `previous`
    - Numerical, month number 1--12
    - Month names `January`, ... ,  `December` (or prefixes `Jan`, ... , `Dec`) 

 - `--week`:
    - Similar as for `--month`, except no month names.
    - Numerical, either week number 1-53 or negative (`-2` for `2 weeks ago`)
    - NOTE: `--week` only works with Python 3.8.0 and newer (I rely on the recently introduced `datetime.date.fromisocalendar` constructor.)

- Also added `today` and `yesterday` as options for the `report_date` positional argument.

If you specify a `--month` or a `--week`, you can also specify `--from` or `--to` -- the latter will override the first or last day of the month, respectively.

This closes #22.

### CODE REVIEW

**Comment by ukrutt** [comment]
@larose I've added integration tests for all of these new branches.

**Comment by larose** [comment]
Same issue for this one. Can you squash your commits?

**Comment by ukrutt** [comment]
I've resolved conflicts and created a squashed branch `month-report-squashed`.  Note that this has been created on top of `csv-output-squashed`, i.e., please merge PR #24 / `csv-output-squashed` BEFORE you merge `month-report-squashed` / PR #25.

**Comment by larose** [comment]
Thanks! Merged!

It looks like the functions that parse a week and a month (`_parse_month`, `_parse_week`, etc.) are handling a lot of cases. I think it would be good to capture them as unit test cases to prevent regression when there will be changes in these functions.

**Comment by ukrutt** [comment]
Yep good idea.  I'll look into adding some unit tests.

**Pull request closed without merging**
