### PR TITLE
Add support for day of the week in --from and --to

### PR DESCRIPTION
**Pull request by kitchoi**
This pull request allows `--from` and `--to` to accept a day of week as values, e.g. `utt report --from monday --to friday`

This is motivated by feedback from my colleagues and myself.  Often we want to know how many hours have been logged since the start of the week. Being able to type `utt report --from monday` would be handy, so that one does not need to work out the date, and can create a shell alias for it.

I understand this will likely cause merge conflicts with the `report` branch.  I'd more than happy to adapt this pull request after the `report` branch is merged.

### CODE REVIEW

**Comment by larose** [comment]
Thanks Kit! I merged the report branch into the master branch. I'll merge your PR once you fix the conflicts.

**Comment by kitchoi** [comment]
I have resolved the merge conflict.  The unit tests are failing on master... :(

I am aware of this scenario:
```
$ utt --now "2018-10-31 09:30" report --from monday --to friday

------- Monday, Oct 29, 2018 (week 44) to Friday, Oct 26, 2018 (week 43) -------

Working Time: 0h00
Break   Time: 0h00
...
```
"today" is a Wednesday.  So "monday" is the Monday in the same week, whereas "friday" is interpreted as the Friday in the week before.

The day of week is always parsed as the nearest one in the past relative to "now".  This is how `utt report <day-of-week>` has been doing.  While the above result is probably not what the user would have meant in the context of `--from` and `--to`, the true meaning is still ambiguous: does the user want the Mon-Fri the week before or the Mon-Fri this week.  Refusing to guess, I think keeping the interpretation inline with `utt report <day-of-week>` is the only sensible option.

The user gets an empty report too if they do something like `--from 2018-12-31 --to 2017-01-01`. One thing we could do is to raise an error if the "from" date is after the "to" date, just to make it more obvious to the user.  (I'd probably do that in a separate pull request though...)

**Comment by larose** [comment]
There are a few solutions to that issue. I was thinking about adding something like this:

- `$ utt report this week`
- `$ utt report last week`
- `$ utt report 2 weeks ago`
- `$ utt report this month`
- `$ utt report last month`

I think it represents more what the user wants.

We could also support `$ utt --from this monday --to this friday` for the current week. For last week: `utt --from last monday --to last friday`. But this seems ambiguous.

We could also do that `--to` depends on `--from`. If `--to` < `--from` and the expression was a relative date (e.g. `friday`) then we interpret `--to` as the next occurence of that relative date (e.g. the next friday after `--from`).

What do you think?

Slightly related: I also thought about adding approximate string matching. For instance: `$ utt report mon` would be parsed as `$ utt report monday`.

I rebased your PR it here https://github.com/larose/utt/compare/kitchoi-report-from-weekday instead of creating a merge commit as I prefer this. Any objections if I merge it?

**Comment by kitchoi** [comment]
> this would mean the "friday" in utt report --to friday and utt report --from monday --to friday may be different, which would be a bit odd. Hence I prefer keeping it simple and sticking to the existing interpretation.

Ah no I was wrong. The friday there would mean the same because --from is default to today. So yeah, I think your idea is reasonable!

**Comment by kitchoi** [comment]
The last two commits implement `--to` to be the next (inclusive) occurrence since the "from" date.
So one gets this:
```
$ utt report --from 2017-01-02 --to friday

-------- Monday, Jan 02, 2017 (week 1) to Friday, Jan 06, 2017 (week 1) --------

```

The same unit tests that fail on master fail here too ... it would make sense to fix master first.

**Comment by larose** [comment]
Merged manually.

**Pull request closed without merging**
