### PR TITLE
simple fix for issue #19

### PR DESCRIPTION
**Pull request by kentaasvang**
catching the exception, ignoring it if is not _invalid value_-error

### CODE REVIEW

**Comment by larose** [comment]
Thank you @kentaasvang, I will look at this PR soon!

**Comment by larose** [comment]
@kentaasvang, you fix looks good and I'll be happy to merge your PR once the following two issues are resolved: 

1) Could you please update your commit message with a message that gives more context? The description you wrote in #19 would be perfect as the commit message.

2) The integration tests now fail, could you fix them? This is the error I'm getting: 

```
$ make test-integration-py3
...
>> ADD
rm -f /root/.local/share/utt/utt.log
utt --now "2014-01-01 8:00" add "  spaces  "
Traceback (most recent call last):
  File "/usr/local/bin/utt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/utt/__main__.py", line 13, in main
    getattr(container, 'command/{}'.format(container.args.command))()
  File "/usr/local/lib/python3.5/dist-packages/utt/commands/add.py", line 12, in __call__
    self._add_entry(Entry(self._now, self._args.name, False))
  File "/usr/local/lib/python3.5/dist-packages/utt/add_entry.py", line 20, in __call__
    insert_new_line_before=insert_new_line_before)
  File "/usr/local/lib/python3.5/dist-packages/utt/add_entry.py", line 25, in _append_line_to_file
    with open(filename, 'rb+') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/utt/utt.log'
```

**Comment by kentaasvang** [comment]
Hi, I have fixed the integration error and changed the commit-message to something more descriptive. Better late than never

**Comment by larose** [comment]
Thanks @kentaasvang! I merged your fix in #61.

**Pull request closed without merging**
