### PR TITLE
CSV output

### PR DESCRIPTION
**Pull request by ukrutt**
This adds a feature to output a single section as CSV, using the `--csv-section` switch.  Only `per_day` has been implemented so far.

NOTE: this feature relies on PR #21 ("Report by day"), since that's the only section available for CSV output added so far  ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by ukrutt** [comment]
@larose -- I have now created a new branch https://github.com/ukrutt/utt/tree/csv-output-squashed -- this is similar to the `csv-output` branch but the conflicts listed above have been resolved... and I've squashed to a single commit.

**Comment by larose** [comment]
@ukrutt can you squash commits in this PR? I can neither git pull it without resolving conflicts nor apply https://patch-diff.githubusercontent.com/raw/larose/utt/pull/24.diff

**Comment by ukrutt** [comment]
Sure, I'll resolve conflicts and squash, and also for #25.

**Comment by larose** [comment]
Thanks! I manually merged this PR.

**Pull request closed without merging**
